Updated test workflow.

diff --git a/.github/workflows/Tests.yml b/.github/workflows/Tests.yml
--- a/.github/workflows/Tests.yml
+++ b/.github/workflows/Tests.yml
@@ -1,108 +1,51 @@
+# --------------------------------------------------------------------------------
+# This workflow was automatically generated by Action Status 1.0.2 (0).
+# (see https://actionstatus.elegantchaos.com for more details)
+# --------------------------------------------------------------------------------
+
 name: Tests
 
 on: [push, pull_request]
 
 jobs:
-    macOS-iOS-tvOS:
-        name: macOS/iOS/tvOS
+
+    macOS-swift-53:
+        name: macOS (Swift 5.3 Nightly)
         runs-on: macOS-latest
+        env:
+            TOOLCHAINS: swift
         steps:
         - name: Checkout
           uses: actions/checkout@v1
-        - name: Swift Version
-          run: swift --version
         - name: Make Logs Directory
           run: mkdir logs
+        - name: Install Toolchain
+          run: |
+            branch="swift-5.3-branch"
+            wget --quiet https://swift.org/builds/$branch/xcode/latest-build.yml
+            grep "download:" < latest-build.yml > filtered.yml
+            sed -e 's/-osx.pkg//g' filtered.yml > stripped.yml
+            sed -e 's/:[^:\/\/]/YML="/g;s/$/"/g;s/ *=/=/g' stripped.yml > snapshot.sh
+            source snapshot.sh
+            echo "Installing Toolchain: $downloadYML"
+            wget --quiet https://swift.org/builds/$branch/xcode/$downloadYML/$downloadYML-osx.pkg
+            sudo installer -pkg $downloadYML-osx.pkg -target /
+            ln -s "/Library/Developer/Toolchains/$downloadYML.xctoolchain/usr/bin" swift-latest
+            sudo xcode-select -s /Applications/Xcode_12_beta.app
+            swift --version
         - name: Xcode Version
-          run: xcodebuild -version
-        - name: XC Pretty
-          run: sudo gem install xcpretty-travis-formatter
-        - name: Build (macOS/Debug)
-          run: set -o pipefail; xcodebuild clean build -workspace . -scheme ActionStatusCore -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-macOS-build-debug.log | xcpretty
-        - name: Build (macOS/Release)
-          run: set -o pipefail; xcodebuild clean build -workspace . -scheme ActionStatusCore -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-macOS-build-release.log | xcpretty
-        - name: Test (macOS/Debug)
           run: |
-            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep ActionStatusCore-Package || true))
-            echo "*$GOTPACKAGE*"
-            if [[ $GOTPACKAGE != "" ]]
-            then
-                SCHEME="ActionStatusCore-Package"
-            else
-                SCHEME="ActionStatusCore"
-            fi
-            set -o pipefail
-            xcodebuild test -workspace . -scheme $SCHEME  -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO  | tee logs/xcodebuild-macOS-test-debug.log | xcpretty
-        - name: Test (macOS/Release)
-          run: |
-            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep ActionStatusCore-Package || true))
-            echo "*$GOTPACKAGE*"
-            if [[ $GOTPACKAGE != "" ]]
-            then
-                SCHEME="ActionStatusCore-Package"
-            else
-                SCHEME="ActionStatusCore"
-            fi
-            set -o pipefail
-            xcodebuild test -workspace . -scheme $SCHEME  -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-macOS-test-release.log | xcpretty
-        - name: Build (iOS/Debug)
-          run: set -o pipefail; xcodebuild clean build -workspace . -scheme ActionStatusCore -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-iOS-build-debug.log | xcpretty
-        - name: Build (iOS/Release)
-          run: set -o pipefail; xcodebuild clean build -workspace . -scheme ActionStatusCore -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-iOS-build-release.log | xcpretty
-        - name: Test (iOS/Debug)
-          run: |
-            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep ActionStatusCore-Package || true))
-            echo "*$GOTPACKAGE*"
-            if [[ $GOTPACKAGE != "" ]]
-            then
-                SCHEME="ActionStatusCore-Package"
-            else
-                SCHEME="ActionStatusCore"
-            fi
-            set -o pipefail
-            xcodebuild test -workspace . -scheme $SCHEME -destination "name=iPhone 11" -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO  | tee logs/xcodebuild-iOS-test-debug.log | xcpretty
-        - name: Test (iOS/Release)
-          run: |
-            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep ActionStatusCore-Package || true))
-            echo "*$GOTPACKAGE*"
-            if [[ $GOTPACKAGE != "" ]]
-            then
-                SCHEME="ActionStatusCore-Package"
-            else
-                SCHEME="ActionStatusCore"
-            fi
-            set -o pipefail
-            xcodebuild test -workspace . -scheme $SCHEME -destination "name=iPhone 11" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-iOS-test-release.log | xcpretty
-        - name: Build (tvOS/Debug)
-          run: set -o pipefail; xcodebuild clean build -workspace . -scheme ActionStatusCore -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-tvOS-build-debug.log | xcpretty
-        - name: Build (tvOS/Release)
-          run: set -o pipefail; xcodebuild clean build -workspace . -scheme ActionStatusCore -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-tvOS-build-release.log | xcpretty
-        - name: Test (tvOS/Debug)
-          run: |
-            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep ActionStatusCore-Package || true))
-            echo "*$GOTPACKAGE*"
-            if [[ $GOTPACKAGE != "" ]]
-            then
-                SCHEME="ActionStatusCore-Package"
-            else
-                SCHEME="ActionStatusCore"
-            fi
-            set -o pipefail
-            xcodebuild test -workspace . -scheme $SCHEME -destination "name=Apple TV" -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO  | tee logs/xcodebuild-tvOS-test-debug.log | xcpretty
-        - name: Test (tvOS/Release)
-          run: |
-            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep ActionStatusCore-Package || true))
-            echo "*$GOTPACKAGE*"
-            if [[ $GOTPACKAGE != "" ]]
-            then
-                SCHEME="ActionStatusCore-Package"
-            else
-                SCHEME="ActionStatusCore"
-            fi
-            set -o pipefail
-            xcodebuild test -workspace . -scheme $SCHEME -destination "name=Apple TV" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-tvOS-test-release.log | xcpretty
+            xcodebuild -version
+            xcrun swift --version
+        - name: Swift Version
+          run: swift --version
+        - name: Build (Release)
+          run: export PATH="swift-latest:$PATH"; swift build -c release
+        - name: Test (Release)
+          run: export PATH="swift-latest:$PATH"; swift test --configuration release -Xswiftc -enable-testing --enable-test-discovery
         - name: Upload Logs
           uses: actions/upload-artifact@v1
+          if: always()
           with:
             name: logs
             path: logs
@@ -111,7 +54,257 @@ jobs:
           if: always()
           with:
             type: ${{ job.status }}
-            job_name: 'macOS/iOS/tvOS'
+            job_name: 'macOS (Swift 5.3 Nightly)'
+            mention_if: 'failure'
+            url: ${{ secrets.SLACK_WEBHOOK }}
+
+
+    macOS-swift-nightly:
+        name: macOS (Swift Development Nightly)
+        runs-on: macOS-latest
+        env:
+            TOOLCHAINS: swift
+        steps:
+        - name: Checkout
+          uses: actions/checkout@v1
+        - name: Make Logs Directory
+          run: mkdir logs
+        - name: Install Toolchain
+          run: |
+            branch="development"
+            wget --quiet https://swift.org/builds/$branch/xcode/latest-build.yml
+            grep "download:" < latest-build.yml > filtered.yml
+            sed -e 's/-osx.pkg//g' filtered.yml > stripped.yml
+            sed -e 's/:[^:\/\/]/YML="/g;s/$/"/g;s/ *=/=/g' stripped.yml > snapshot.sh
+            source snapshot.sh
+            echo "Installing Toolchain: $downloadYML"
+            wget --quiet https://swift.org/builds/$branch/xcode/$downloadYML/$downloadYML-osx.pkg
+            sudo installer -pkg $downloadYML-osx.pkg -target /
+            ln -s "/Library/Developer/Toolchains/$downloadYML.xctoolchain/usr/bin" swift-latest
+            sudo xcode-select -s /Applications/Xcode_12_beta.app
+            swift --version
+        - name: Xcode Version
+          run: |
+            xcodebuild -version
+            xcrun swift --version
+        - name: Swift Version
+          run: swift --version
+        - name: Build (Release)
+          run: export PATH="swift-latest:$PATH"; swift build -c release
+        - name: Test (Release)
+          run: export PATH="swift-latest:$PATH"; swift test --configuration release -Xswiftc -enable-testing --enable-test-discovery
+        - name: Upload Logs
+          uses: actions/upload-artifact@v1
+          if: always()
+          with:
+            name: logs
+            path: logs
+        - name: Slack Notification
+          uses: elegantchaos/slatify@master
+          if: always()
+          with:
+            type: ${{ job.status }}
+            job_name: 'macOS (Swift Development Nightly)'
+            mention_if: 'failure'
+            url: ${{ secrets.SLACK_WEBHOOK }}
+
+
+    xcode-swift-53:
+        name: Xcode (Swift 5.3 Nightly)
+        runs-on: macOS-latest
+        env:
+            TOOLCHAINS: swift
+        steps:
+        - name: Checkout
+          uses: actions/checkout@v1
+        - name: Make Logs Directory
+          run: mkdir logs
+        - name: Install Toolchain
+          run: |
+            branch="swift-5.3-branch"
+            wget --quiet https://swift.org/builds/$branch/xcode/latest-build.yml
+            grep "download:" < latest-build.yml > filtered.yml
+            sed -e 's/-osx.pkg//g' filtered.yml > stripped.yml
+            sed -e 's/:[^:\/\/]/YML="/g;s/$/"/g;s/ *=/=/g' stripped.yml > snapshot.sh
+            source snapshot.sh
+            echo "Installing Toolchain: $downloadYML"
+            wget --quiet https://swift.org/builds/$branch/xcode/$downloadYML/$downloadYML-osx.pkg
+            sudo installer -pkg $downloadYML-osx.pkg -target /
+            ln -s "/Library/Developer/Toolchains/$downloadYML.xctoolchain/usr/bin" swift-latest
+            sudo xcode-select -s /Applications/Xcode_12_beta.app
+            swift --version
+        - name: Xcode Version
+          run: |
+            xcodebuild -version
+            xcrun swift --version
+        - name: XC Pretty
+          run: sudo gem install xcpretty-travis-formatter
+        - name: Detect Workspace & Scheme (iOS)
+          run: |
+            WORKSPACE="ActionStatusCore.xcworkspace"
+            if [[ ! -e "$WORKSPACE" ]]
+            then
+            WORKSPACE="."
+            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep ActionStatusCore-Package || true))
+            if [[ $GOTPACKAGE != "" ]]
+            then
+            SCHEME="ActionStatusCore-Package"
+            else
+            SCHEME="ActionStatusCore"
+            fi
+            else
+            SCHEME="ActionStatusCore-iOS"
+            fi
+            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
+        - name: Build (iOS Release)
+          run: |
+            source "setup.sh"
+            echo "Building workspace $WORKSPACE scheme $SCHEME."
+            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-iOS-build-release.log | xcpretty
+        - name: Test (iOS Release)
+          run: |
+            source "setup.sh"
+            echo "Testing workspace $WORKSPACE scheme $SCHEME."
+            xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=iPhone 11" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-iOS-test-release.log | xcpretty
+        - name: Detect Workspace & Scheme (tvOS)
+          run: |
+            WORKSPACE="ActionStatusCore.xcworkspace"
+            if [[ ! -e "$WORKSPACE" ]]
+            then
+            WORKSPACE="."
+            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep ActionStatusCore-Package || true))
+            if [[ $GOTPACKAGE != "" ]]
+            then
+            SCHEME="ActionStatusCore-Package"
+            else
+            SCHEME="ActionStatusCore"
+            fi
+            else
+            SCHEME="ActionStatusCore-tvOS"
+            fi
+            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
+        - name: Build (tvOS Release)
+          run: |
+            source "setup.sh"
+            echo "Building workspace $WORKSPACE scheme $SCHEME."
+            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-tvOS-build-release.log | xcpretty
+        - name: Test (tvOS Release)
+          run: |
+            source "setup.sh"
+            echo "Testing workspace $WORKSPACE scheme $SCHEME."
+            xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=Apple TV" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-tvOS-test-release.log | xcpretty
+        - name: Upload Logs
+          uses: actions/upload-artifact@v1
+          if: always()
+          with:
+            name: logs
+            path: logs
+        - name: Slack Notification
+          uses: elegantchaos/slatify@master
+          if: always()
+          with:
+            type: ${{ job.status }}
+            job_name: 'Xcode (Swift 5.3 Nightly)'
+            mention_if: 'failure'
+            url: ${{ secrets.SLACK_WEBHOOK }}
+
+
+    xcode-swift-nightly:
+        name: Xcode (Swift Development Nightly)
+        runs-on: macOS-latest
+        env:
+            TOOLCHAINS: swift
+        steps:
+        - name: Checkout
+          uses: actions/checkout@v1
+        - name: Make Logs Directory
+          run: mkdir logs
+        - name: Install Toolchain
+          run: |
+            branch="development"
+            wget --quiet https://swift.org/builds/$branch/xcode/latest-build.yml
+            grep "download:" < latest-build.yml > filtered.yml
+            sed -e 's/-osx.pkg//g' filtered.yml > stripped.yml
+            sed -e 's/:[^:\/\/]/YML="/g;s/$/"/g;s/ *=/=/g' stripped.yml > snapshot.sh
+            source snapshot.sh
+            echo "Installing Toolchain: $downloadYML"
+            wget --quiet https://swift.org/builds/$branch/xcode/$downloadYML/$downloadYML-osx.pkg
+            sudo installer -pkg $downloadYML-osx.pkg -target /
+            ln -s "/Library/Developer/Toolchains/$downloadYML.xctoolchain/usr/bin" swift-latest
+            sudo xcode-select -s /Applications/Xcode_12_beta.app
+            swift --version
+        - name: Xcode Version
+          run: |
+            xcodebuild -version
+            xcrun swift --version
+        - name: XC Pretty
+          run: sudo gem install xcpretty-travis-formatter
+        - name: Detect Workspace & Scheme (iOS)
+          run: |
+            WORKSPACE="ActionStatusCore.xcworkspace"
+            if [[ ! -e "$WORKSPACE" ]]
+            then
+            WORKSPACE="."
+            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep ActionStatusCore-Package || true))
+            if [[ $GOTPACKAGE != "" ]]
+            then
+            SCHEME="ActionStatusCore-Package"
+            else
+            SCHEME="ActionStatusCore"
+            fi
+            else
+            SCHEME="ActionStatusCore-iOS"
+            fi
+            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
+        - name: Build (iOS Release)
+          run: |
+            source "setup.sh"
+            echo "Building workspace $WORKSPACE scheme $SCHEME."
+            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-iOS-build-release.log | xcpretty
+        - name: Test (iOS Release)
+          run: |
+            source "setup.sh"
+            echo "Testing workspace $WORKSPACE scheme $SCHEME."
+            xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=iPhone 11" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-iOS-test-release.log | xcpretty
+        - name: Detect Workspace & Scheme (tvOS)
+          run: |
+            WORKSPACE="ActionStatusCore.xcworkspace"
+            if [[ ! -e "$WORKSPACE" ]]
+            then
+            WORKSPACE="."
+            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep ActionStatusCore-Package || true))
+            if [[ $GOTPACKAGE != "" ]]
+            then
+            SCHEME="ActionStatusCore-Package"
+            else
+            SCHEME="ActionStatusCore"
+            fi
+            else
+            SCHEME="ActionStatusCore-tvOS"
+            fi
+            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
+        - name: Build (tvOS Release)
+          run: |
+            source "setup.sh"
+            echo "Building workspace $WORKSPACE scheme $SCHEME."
+            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-tvOS-build-release.log | xcpretty
+        - name: Test (tvOS Release)
+          run: |
+            source "setup.sh"
+            echo "Testing workspace $WORKSPACE scheme $SCHEME."
+            xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=Apple TV" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-tvOS-test-release.log | xcpretty
+        - name: Upload Logs
+          uses: actions/upload-artifact@v1
+          if: always()
+          with:
+            name: logs
+            path: logs
+        - name: Slack Notification
+          uses: elegantchaos/slatify@master
+          if: always()
+          with:
+            type: ${{ job.status }}
+            job_name: 'Xcode (Swift Development Nightly)'
             mention_if: 'failure'
             url: ${{ secrets.SLACK_WEBHOOK }}
 
